import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { createServer } from 'node:http';
import type { AddressInfo } from 'node:net';
import { CareerStore, CareerError, careerUrl } from '../server/career-store.ts';
import { Vault } from '../server/vault.ts';
import { handleCareerApi } from '../server/career-api.ts';

const setup=()=>{const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON; CREATE TABLE prospects (id TEXT PRIMARY KEY);');return {db,store:new CareerStore(db)};};
const pdf=Buffer.from('%PDF-1.4\n1 0 obj<</Type/Catalog>>endobj\n%%EOF');
const job=(store:CareerStore)=>store.saveJob({url:'https://jobs.example.org/apply/17?utm_source=test&job=17',title:'Engineer',company:'Fiction',location:'Paris'});
const resume=(store:CareerStore)=>store.saveResume({name:'CV',filename:'cv.pdf',mime:'application/pdf',bytes:pdf});

test('profile, CV validation, canonical jobs and idempotent application',()=>{const {db,store}=setup();const p=store.saveProfile({firstName:'Ada',answers:{work_authorization:false},preferences:{remote:false}});assert.equal(p.answers.work_authorization,false);assert.throws(()=>store.saveProfile({firstName:'Ada',state:'submitted'}),CareerError);assert.throws(()=>store.saveResume({name:'bad',filename:'bad.pdf',mime:'application/pdf',bytes:Buffer.from('bad')}),CareerError);const r=resume(store),j=job(store);assert.equal(store.getResume(r.id).bytes.toString(),pdf.toString());assert.equal(store.saveJob({url:'https://jobs.example.org/apply/17?job=17',title:'Engineer',company:'Fiction'}).id,j.id);const a=store.createApplication({jobId:j.id,resumeId:r.id});assert.equal(store.createApplication({jobId:j.id,resumeId:r.id}).id,a.id);assert.equal(store.listApplications().length,1);assert.throws(()=>store.deleteResume(r.id),CareerError);db.close();});

test('durable submit marker, uncertain recovery and explicit resolution',()=>{const {db,store}=setup();const a=store.createApplication({jobId:job(store).id,resumeId:resume(store).id});store.claimRun(a.id);assert.throws(()=>store.claimRun(a.id),CareerError);store.markSubmitting(a.id);store.recoverInterruptedRuns();assert.equal(store.getApplication(a.id).state,'uncertain');assert.throws(()=>store.claimRun(a.id),CareerError);assert.throws(()=>store.resolveUncertain(a.id,{resolution:'not_submitted',detail:''}),CareerError);store.resolveUncertain(a.id,{resolution:'not_submitted',detail:'Le portail indique aucune candidature.'});assert.equal(store.getApplication(a.id).state,'draft');store.claimRun(a.id);store.markSubmitting(a.id);store.finishRun(a.id,{state:'submitted',message:'',missingFields:[],receipt:{url:'https://jobs.example.org/thanks',text:'Application received',reference:'ABC-1',observedAt:new Date().toISOString()}});assert.equal(store.getMetrics().submitted,1);assert.throws(()=>store.claimRun(a.id),CareerError);assert.equal(store.listEvents().filter(e=>e.kind==='submitted').length,1);db.close();});

test('public updates cannot forge state, receipt or submit timestamp',()=>{const {db,store}=setup();const a=store.createApplication({jobId:job(store).id,resumeId:resume(store).id});for(const key of ['state','receipt','submittedAt','lastError'])assert.throws(()=>store.updateApplication(a.id,{[key]:'submitted'}),CareerError);store.updateApplication(a.id,{answers:{permission:false},outcome:'interview'});assert.equal(store.getApplication(a.id).answers.permission,false);assert.equal(store.getMetrics().interviews,1);db.close();});

test('profile change invalidates preparation and is blocked during an active run',()=>{const {db,store}=setup();const a=store.createApplication({jobId:job(store).id,resumeId:resume(store).id});store.claimRun(a.id);store.finishRun(a.id,{state:'ready',message:'',missingFields:[],receipt:null});store.saveProfile({firstName:'Ada'});assert.equal(store.getApplication(a.id).state,'draft');store.claimRun(a.id);assert.throws(()=>store.saveProfile({firstName:'Grace'}),CareerError);db.close();});

test('URL validation rejects local, credentials and dangerous schemes',()=>{for(const url of ['http://example.org/job','https://127.0.0.1/job','https://user:pass@example.org/job','file:///etc/passwd','https://localhost/job'])assert.throws(()=>careerUrl(url),CareerError);assert.equal(careerUrl('https://example.org/job?utm_source=x&id=2#part'),'https://example.org/job?id=2');});

test('submitted and uncertain applications keep CV and answers immutable while notes remain editable',()=>{const {db,store}=setup();const first=resume(store),second=store.saveResume({name:'Second',filename:'second.pdf',mime:'application/pdf',bytes:Buffer.concat([pdf,Buffer.from('other')])});const a=store.createApplication({jobId:job(store).id,resumeId:first.id});store.claimRun(a.id);store.markSubmitting(a.id);store.finishRun(a.id,{state:'submitted',message:'',missingFields:[],receipt:{url:'https://jobs.example.org/thanks?access_token=secret123&session_id=abc&job=17&auth_code=xyz',text:'Application received',reference:'ABC-1',observedAt:new Date().toISOString()}});assert.equal(store.getApplication(a.id).receipt?.url,'https://jobs.example.org/thanks?job=17');for(const patch of [{resumeId:second.id},{answers:{permission:true}},{prospectId:null}])assert.throws(()=>store.updateApplication(a.id,patch),CareerError);store.updateApplication(a.id,{notes:'Interview next week',outcome:'interview',nextActionAt:'2026-10-10'});assert.equal(store.getApplication(a.id).resumeId,first.id);assert.equal(store.getApplication(a.id).notes,'Interview next week');const b=store.createApplication({jobId:store.saveJob({url:'https://jobs.example.org/apply/18',title:'Other',company:'Fiction'}).id,resumeId:first.id});store.claimRun(b.id);store.markSubmitting(b.id);store.recoverInterruptedRuns();assert.throws(()=>store.updateApplication(b.id,{answers:{permission:true}}),CareerError);store.updateApplication(b.id,{notes:'Verify with company'});assert.equal(store.getApplication(b.id).notes,'Verify with company');db.close();});

test('HTTP resume upload handles 5 MiB, rejects >10 MiB and downloads Unicode filename',async()=>{const {db,store}=setup();const vault=new Vault(db);const server=createServer(async(req,res)=>{await handleCareerApi(req,res,new URL(req.url||'/', 'http://127.0.0.1'),{store,vault,runner:{start(){throw new Error('not used');},resume(){throw new Error('not used');},isBusy(){return false;},hasPausedSession(){return false;},async stop(){}},discovery:{async discover(){return {offers:[],note:''};}},demo:false});});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address() as AddressInfo,base=`http://127.0.0.1:${address.port}`;try{const bytes=Buffer.alloc(5*1024*1024,65);Buffer.from('%PDF-').copy(bytes);const upload=await fetch(`${base}/api/career/resumes`,{method:'POST',headers:{'Content-Type':'application/json','X-Anima-Request':'1'},body:JSON.stringify({name:'CV',filename:'CV_候補.pdf',mime:'application/pdf',base64:bytes.toString('base64')})});assert.equal(upload.status,201);const meta=await upload.json() as {id:string;size:number};assert.equal(meta.size,bytes.length);const download=await fetch(`${base}/api/career/resumes/${meta.id}/download`);assert.equal(download.status,200);const disposition=download.headers.get('content-disposition')||'';assert.match(disposition,/filename="CV_.*\.pdf"/);assert.match(disposition,/filename\*=UTF-8''CV_%E5%80%99%E8%A3%9C\.pdf/);assert.deepEqual(Buffer.from(await download.arrayBuffer()),bytes);const oversized=Buffer.alloc(10*1024*1024+1,65);Buffer.from('%PDF-').copy(oversized);const rejected=await fetch(`${base}/api/career/resumes`,{method:'POST',headers:{'Content-Type':'application/json','X-Anima-Request':'1'},body:JSON.stringify({name:'CV',filename:'large.pdf',mime:'application/pdf',base64:oversized.toString('base64')})});assert.equal(rejected.status,413);assert.equal(store.listResumes().length,1);}finally{await new Promise<void>(resolve=>server.close(()=>resolve()));db.close();}});
