import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { Vault } from '../server/vault.ts';
import { CareerError } from '../server/career-store.ts';

test('vault encrypts secrets and binds credentials to exact origin',()=>{const db=new DatabaseSync(':memory:');const vault=new Vault(db);assert.deepEqual(vault.status(),{initialized:false,unlocked:false});vault.initialize('a long private phrase');const saved=vault.saveCredential({origin:'https://careers.example.org',label:'Career',username:'ada@example.org',password:'top-secret-pass'});const raw=(db.prepare('SELECT ciphertext FROM career_credentials').get() as {ciphertext:Uint8Array}).ciphertext;assert.equal(Buffer.from(raw).includes(Buffer.from('top-secret-pass')),false);assert.equal(vault.getCredential(saved.id,'https://careers.example.org').password,'top-secret-pass');assert.throws(()=>vault.getCredential(saved.id,'https://evil.careers.example.org'),CareerError);vault.lock();assert.throws(()=>vault.getCredential(saved.id,'https://careers.example.org'),CareerError);assert.throws(()=>vault.unlock('wrong phrase'),CareerError);vault.unlock('a long private phrase');assert.equal(vault.getCredential(saved.id,'https://careers.example.org').username,'ada@example.org');db.close();});

test('tampered ciphertext fails authentication',()=>{const db=new DatabaseSync(':memory:');const vault=new Vault(db);vault.initialize('a long private phrase');const saved=vault.saveCredential({origin:'https://careers.example.org',label:'Career',username:'ada',password:'secret'});db.prepare("UPDATE career_credentials SET tag=randomblob(16) WHERE id=?").run(saved.id);assert.throws(()=>vault.getCredential(saved.id,'https://careers.example.org'),CareerError);vault.lock();db.close();});

test('password leading and trailing spaces survive encryption unchanged',()=>{const db=new DatabaseSync(':memory:');const vault=new Vault(db);vault.initialize('a long private phrase');const saved=vault.saveCredential({origin:'https://careers.example.org',label:'Career',username:'ada',password:'  keep spaces  '});assert.equal(vault.getCredential(saved.id,'https://careers.example.org').password,'  keep spaces  ');vault.lock();vault.unlock('a long private phrase');assert.equal(vault.getCredential(saved.id,'https://careers.example.org').password,'  keep spaces  ');db.close();});
